method: ISCNet
seed: 10
weight: out/balance/model.pt
device:
  use_gpu: True
  gpu_ids: '1'
  num_workers: 0
data:
  dataset: scannet
  split: splits/fullscan
  num_point: 80000
  num_target: 256
  vote_factor: 1
  cluster_sampling: seed_fps
  ap_iou_thresh: 0.25
  no_height: True
  use_color_detection: False
  use_color_completion: False
  shapenet_path: ShapeNetv2_data
  points_unpackbits: True
  points_subsample: [1024, 1024]
  hidden_dim: 512
  c_dim: 512
  z_dim: 32
  dim: 3
  completion_limit_in_train: 10
  use_cls_for_completion: False
  skip_propagate: True
model:
  decoder: simple
  encoder: resnet18
  encoder_latent: null
  decoder_kwargs: {}
  encoder_kwargs: {}
  encoder_latent_kwargs: {}
  multi_gpu: false
  c_dim: 2048
  z_dim: 64
  use_camera: false
  dmc_weight_prior: 10.
test:
  phase: 'completion'
  batch_size: 1
  use_cls_nms: True
  use_3d_nms: True
  ap_iou_thresholds: [0.5]
  faster_eval: False
  nms_iou: 0.25
  use_old_type_nms: False
  per_class_proposal: True
  conf_thresh: 0.05
  evaluate_mesh_mAP: False
  threshold: 0.5
generation:
  generate_mesh: True
  resolution_0: 32
  upsampling_steps: 0
  use_sampling: False
  refinement_step: 0
  simplify_nfaces: Null
  dump_threshold: 0.5
  dump_results: True
demo:
  phase: 'completion'
log:
  vis_path: visualization
  save_results: True
  vis_step: 100
  print_step: 10
  path: out/iscnet
